//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminSeguridad
{
    using System;
    using System.Collections.Generic;
    
    public partial class Permisos_Menus
    {
        public int MenuID { get; set; }
        public int PermisoID { get; set; }
        public bool PermisoLectura { get; set; }
        public bool PermisoEscritura { get; set; }
        public bool PermisoModificacion { get; set; }
        public bool PermisoEliminacion { get; set; }
    
        public virtual Menu Menu { get; set; }
        public virtual Permiso Permiso { get; set; }
    }
}
