//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminSeguridad
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuarios_Permisos
    {
        public int UsuarioID { get; set; }
        public int PermisoID { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public System.DateTime FechaActualizacion { get; set; }
    
        public virtual Permiso Permiso { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
